[package]
name = "device-babysitter"
version = "0.1.0"
authors = ["Zeyi Fan <zeyi@fb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.6.2"
structopt = "0.3.17"
